version: "3.8"
services:
  db:
    image: postgres:12
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
