# Generated by Django 4.2.2 on 2023-06-29 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_time',
            field=models.DateField(default=datetime.datetime(2023, 6, 29, 22, 54, 48, 37065)),
        ),
    ]
