# Generated by Django 4.2.2 on 2023-06-27 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_poll_start_time_alter_question_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_time',
            field=models.DateField(default=datetime.datetime(2023, 6, 27, 21, 19, 28, 406733)),
        ),
    ]
