# Generated by Django 4.2.2 on 2023-06-27 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_rename_text_answer_answer_text_alter_answer_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_time',
            field=models.DateField(default=datetime.datetime(2023, 6, 27, 23, 33, 39, 394483)),
        ),
    ]
