# Generated by Django 4.2.2 on 2023-06-30 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_poll_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_time',
            field=models.DateField(default=datetime.datetime(2023, 6, 30, 8, 55, 23, 585261)),
        ),
    ]
