# Generated by Django 4.2.2 on 2023-06-30 09:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_poll_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=4096)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_time',
            field=models.DateField(default=datetime.datetime(2023, 6, 30, 9, 23, 57, 465171)),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='polls.user'),
        ),
    ]
